version: '2'
services:
  shop-place-app:
    image: shop-place-app
    ports:
      - "8080:8080"
    depends_on:
      - mypostgres
  mypostgres:
    image: postgres
    volumes:
      - ./src/main/resources/db.sql:/docker-entrypoint-initdb.d/db.sql
      - db-data:/var/lib/postgresql/data/
    ports:
      - "5445:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb

volumes:
  db-data: